### PR TITLE
Randomize the list of instances

### PR DESCRIPTION
**Pull request by hakaba-hitoyo**
The list of instances is now some non-semantic order (physical position in the database?). It has better to be randomized.

### CODE REVIEW

**Comment by hakaba-hitoyo** [comment]
It is not fair nor user friendly that the table of instances is now fixed ordered. Why always we have to see mastodon.xyz, awoo.space, social.tchncs.de and other sticky instances.

**Comment by Technowix** [comment]
might be cool to, like before, add the security/stability/longevity of each instance into account too. Seem to be gone rightnow :v

**Comment by TheKinrar** [comment]
I'll work on that soon @Technowix, looks like a good idea :)

**Comment by Technowix** [comment]
After some tough might be better to have a list of "passable" instances, that get enought uptime / security / etc, and then randomize them ? :)

**Comment by TheKinrar** [comment]
That's what I'm doing on the wizard in fact. Okay. :)

**Comment by hakaba-hitoyo** [comment]
The sticky (top positioned) instances are not always stable nor user-friendly, because:

(5th) socially.constructed.space is now down.

(8th) social.diskseven.com is private.

(9th) social.gestaltzerfall.net is now down.

(10th) social.imirhil.fr is private.

I suppose that randomize is better (not the best) than the fixed order.

**Comment by Technowix** [comment]
Of course fixed is shit, but "filtered" might be better here

**Comment by hakaba-hitoyo** [comment]
😍

**Pull request merged**
