### PR TITLE
Update Chinese (Simplified) translations

### PR DESCRIPTION
**Pull request by SerCom-KC**
This PR also changes the language code from `zh` to `zh-CN` and applied the `font-weight` fix inspired by #39 and 6721613481fde1b58955adbf8b8fafa308aa0244.

### CODE REVIEW

**Comment by SerCom-KC** [comment]
@Gargron ?

**Comment by SerCom-KC** [comment]
@Gargron I've changed the language code back, please check :P

**Comment by SerCom-KC** [comment]
Looks like the actual site hasn't updated yet...

**Comment by Gargron** [comment]
It's not automatic. I'll need to pull the code, re-build, and upload to the host. I'll do it soon

**Pull request merged**
